name: DBH
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: 
    - self-hosted
    - laber-1
    - labar-2
    
    steps:
    - name: Git pull
      run: |
        cd
        git init
<<<<<<< Updated upstream
        git pull https://github.com/yener5855/echo-bot.git
=======
        git pull git@github.com:yener5855/echo-bot.git
>>>>>>> Stashed changes
        npm i
